import libraries that will be needed

In [1]:
import pandas as pd
import numpy as np

Pandas has 2 objects namely dataframe and series

# Object Series
Object series have one data dimension. Do not have a column name because it only have one column and have an index.

In [2]:
data = [15,20,25,30,35,40,45,50,55,60,65,70,75,80]

converting data to series form.

In [3]:
data = pd.Series(data)

In [4]:
data

0     15
1     20
2     25
3     30
4     35
5     40
6     45
7     50
8     55
9     60
10    65
11    70
12    75
13    80
dtype: int64

converting data series to array.

In [5]:
data.values

array([15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80],
      dtype=int64)

Displaying index.

The index is a range, where the starting point is inclusive of the range and the stop point is exclusive to the range.

In [6]:
data.index

RangeIndex(start=0, stop=14, step=1)

How to call the data

In [8]:
data [2]

25

implicit index is the default index.

we can define an index called an explicit index and it must be equal to the number of data.

In [9]:
data1 = [11,22,33,44,55]
data1 = pd.Series(data1)
print(data1,'\n') 
print(data1.values) #array

0    11
1    22
2    33
3    44
4    55
dtype: int64 

[11 22 33 44 55]


In [10]:
data1 = [11,22,33,44,55]
data1 = pd.Series(data1, index=['a','b','c','d','e'])
print(data1,'\n') 
print(data1.values) #array

a    11
b    22
c    33
d    44
e    55
dtype: int64 

[11 22 33 44 55]


In [11]:
list(range(2,20,3))

[2, 5, 8, 11, 14, 17]

In [12]:
#indeks implisit
data1['a']

11

We can call the implicit index and explicit one.

In [13]:
#index explisit
data1[1]

22

when implicit index and explicit index exist the same. When we call the data, it will only rely on the explicit index data. or it can cause an error

In [15]:
data2 = [11,22,33,44,55]
data2 = pd.Series(data2, index=[3,2,5,7,8])

In [16]:
data2[3]

11

In [17]:
data2[1]

KeyError: 1

we will call data b to c.

In [18]:
data1['b':'c']

b    22
c    33
dtype: int64

but we can slicing the implicit index, then only the starting point will appear. because the implicit index is a range.

In [19]:
data1[1:2]

b    22
dtype: int64